#
###################################
# Site wide configuration
####################################
#
title:       "Chris Cawley"
description: "Resume for Chris Cawley"
url:         "http://chriscawley.com"

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Chicago
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:categories/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Chris Cawley
  avatar: avatar.png
  job: "Filmmaker"
  bio: "I'm a full stack web engineer. I build C# and Javascript webapps."
  email: "cscawley@mac.com"
  disqus-shortname:
  twitter: cscawley
  facebook:
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: cscawley
  gitlab: #cscawley
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username